import Link from "next/link";
import { RecentPage } from "@/lib/s3";
import { Clock } from "lucide-react";

interface RecentPagesProps {
  pages: RecentPage[];
}

export default function RecentPages({ pages }: RecentPagesProps) {
  if (pages.length === 0) {
    return null;
  }

  const formatTimeAgo = (date: Date) => {
    const now = new Date();
    const diffInMinutes = Math.floor(
      (now.getTime() - date.getTime()) / (1000 * 60)
    );

    if (diffInMinutes < 1) return "Just now";
    if (diffInMinutes < 60) return `${diffInMinutes}m ago`;

    const diffInHours = Math.floor(diffInMinutes / 60);
    if (diffInHours < 24) return `${diffInHours}h ago`;

    const diffInDays = Math.floor(diffInHours / 24);
    if (diffInDays < 7) return `${diffInDays}d ago`;

    return date.toLocaleDateString();
  };

  const clayColors = [
    "bg-clay-peach",
    "bg-clay-mint",
    "bg-clay-lavender",
    "bg-clay-sky",
  ];

  return (
    <section className="py-12 sm:py-16 bg-card/20">
      <div className="max-w-4xl mx-auto px-4 sm:px-6">
        <h2 className="text-2xl sm:text-3xl font-bold text-center text-foreground mb-8 sm:mb-12">
          Recently Generated Pages
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6">
          {pages.map((page, index) => (
            <Link
              key={page.slug}
              href={`/${page.slug}`}
              className="group block bg-card clay-shadow clay-rounded-lg hover:clay-shadow-hover hover:-translate-y-1 transition-all duration-200 overflow-hidden flex flex-col h-full"
            >
              <div className="p-4 sm:p-6 flex-1">
                <div className="flex items-start justify-between mb-3">
                  <h3 className="font-semibold text-foreground group-hover:text-primary transition-colors line-clamp-2 text-sm sm:text-base">
                    {page.title}
                  </h3>
                </div>

                <div className="flex items-center text-muted-foreground text-xs sm:text-sm">
                  <Clock className="w-3 h-3 sm:w-4 sm:h-4 mr-1 flex-shrink-0" />
                  <span>{formatTimeAgo(page.lastModified)}</span>
                </div>

                <div className="mt-3 pt-3 border-t border-border">
                  <p className="text-xs text-muted-foreground font-mono break-all bg-input clay-inset px-2 py-1.5 clay-rounded-sm">
                    everywebsite.ai/{page.slug}
                  </p>
                </div>
              </div>

              <div className={`h-2 ${clayColors[index % clayColors.length]} clay-rounded-sm mx-4 mb-4 transform scale-x-0 group-hover:scale-x-100 transition-transform duration-200 origin-left clay-shadow-sm`}></div>
            </Link>
          ))}
        </div>

        <div className="text-center mt-8">
          <p className="text-muted-foreground text-sm font-medium bg-card clay-shadow-sm clay-rounded-md px-4 py-2 inline-block">
            These pages were generated by other users. Click to view them!
          </p>
        </div>
      </div>
    </section>
  );
}
