import Link from "next/link";
import { RecentPage } from "@/lib/s3";
import { Clock } from "lucide-react";

interface RecentPagesProps {
  pages: RecentPage[];
}

export default function RecentPages({ pages }: RecentPagesProps) {
  if (pages.length === 0) {
    return null;
  }

  const formatTimeAgo = (date: Date) => {
    const now = new Date();
    const diffInMinutes = Math.floor(
      (now.getTime() - date.getTime()) / (1000 * 60)
    );

    if (diffInMinutes < 1) return "Just now";
    if (diffInMinutes < 60) return `${diffInMinutes}m ago`;

    const diffInHours = Math.floor(diffInMinutes / 60);
    if (diffInHours < 24) return `${diffInHours}h ago`;

    const diffInDays = Math.floor(diffInHours / 24);
    if (diffInDays < 7) return `${diffInDays}d ago`;

    return date.toLocaleDateString();
  };

  return (
    <section className="py-12 sm:py-16 bg-yellow-300 border-y-4 border-black">
      <div className="max-w-6xl mx-auto px-4 sm:px-6">
        <h2 className="text-3xl sm:text-4xl font-black uppercase text-center text-black mb-12 sm:mb-16 tracking-tight">
          Recently Generated Pages
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 sm:gap-8">
          {pages.map((page) => (
            <Link
              key={page.slug}
              href={`/${page.slug}`}
              className="group block bg-white border-4 border-black shadow-brutal hover:shadow-brutal-sm hover:translate-x-[2px] hover:translate-y-[2px] active:shadow-none active:translate-x-1 active:translate-y-1 transition-all flex flex-col h-full"
            >
              <div className="p-5 sm:p-6 flex-1">
                <div className="flex items-start justify-between mb-4">
                  <h3 className="font-black uppercase text-black group-hover:text-pink-500 transition-colors line-clamp-2 text-base sm:text-lg tracking-tight">
                    {page.title}
                  </h3>
                </div>

                <div className="flex items-center text-black font-bold text-xs sm:text-sm mb-4">
                  <Clock className="w-4 h-4 sm:w-5 sm:h-5 mr-2 flex-shrink-0 stroke-[3]" />
                  <span>{formatTimeAgo(page.lastModified)}</span>
                </div>

                <div className="pt-4 border-t-2 border-black">
                  <p className="text-xs font-bold text-black font-mono break-all">
                    everywebsite.ai/{page.slug}
                  </p>
                </div>
              </div>

              <div className="h-2 bg-pink-400 border-t-4 border-black"></div>
            </Link>
          ))}
        </div>

        <div className="text-center mt-10 sm:mt-12">
          <p className="text-black font-bold text-sm sm:text-base uppercase bg-white border-4 border-black shadow-brutal inline-block px-6 py-3">
            These pages were generated by other users. Click to view them!
          </p>
        </div>
      </div>
    </section>
  );
}
